ChecklistSeiscomp/urls.py
from django.urls import path
from . import views

app_name = 'ChecklistSeiscomp'

urlpatterns = [
    path('', views.create_view, name='home'),
    path('statistic_view/', views.statistic_view, name='statistic_view'),
    path('create_view/', views.create_view, name='create_view'),
    path('list_view', views.list_view, name='list_view'),
    path('operator_view', views.operator_view, name='operator_view'),
    path('operator_delete/<int:id>/', views.operator_delete, name='operator_delete'),
    path('operator_update/<int:id>/', views.operator_update, name='operator_update'),
    path('data_delete/<int:id>/', views.data_delete, name='data_delete'),
    path('export_excel/<int:id>', views.export_excel, name='export_excel'),
    path('detail_view/<int:id>', views.detail_view, name='detail_view'),
    path('export_pdf_instant/', views.export_pdf_instant, name='export_pdf_instant'),
    path('send_to_gcp_ss/', views.send_to_gcp_ss, name='send_to_gcp_ss'),
    path('station_list_view', views.station_list_view, name='station_list_view'),
    path('station_list_delete/<int:id>/', views.station_list_delete, name='station_list_delete'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

eBAST/urls.py
from django.contrib import admin
from django.urls import path, include
from ChecklistSeiscomp import views
from accounts import views as views_account

app_name = 'ChecklistSeiscomp'

urlpatterns = [
    path('', views.create_view),
    path('admin/', admin.site.urls),
    path('checklist-seiscomp/', include('ChecklistSeiscomp.urls')),
    path('', include('accounts.urls')),
]

ChecklistSeiscomp/models.py
from django.db import models
from datetime import datetime

# Create your models here.
KELOMPOK = (
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
)

WAKTU = (
    ('12:00 WIB', '12:00 WIB'),
    ('18:00 WIB', '18:00 WIB'),
    ('00:00 WIB', '00:00 WIB')
)

class StationListModel(models.Model):
    kode = models.CharField(max_length=10)
    lokasi = models.CharField(max_length=200)
    tipe = models.CharField(max_length=50)

    def __str__(self):
        return self.kode
    
class ChecklistSeiscompModel(models.Model):
 
    # fields of the model
    tanggal = models.DateField()
    jam = models.CharField(max_length=20, choices=WAKTU, default='12:00 WIB')
    kelompok = models.IntegerField(choices=KELOMPOK, default=1)
    operator = models.TextField(null=True,)
    gaps = models.TextField(max_length=500, null=True, blank=True)
    spikes = models.TextField(max_length=500, null=True, blank=True)
    blanks = models.TextField(max_length=500, null=True, blank=True)
    slmon = models.PositiveIntegerField(null=True, blank=True, default=0)
    count_gaps = models.IntegerField(default=0, blank=True)
    count_spikes = models.IntegerField(default=0, blank=True)
    count_blanks = models.IntegerField(default=0, blank=True)

    def save(self, *args, **kwargs):
        seismograph_list = StationListModel.objects.values_list('kode', flat=True)

        def remove_accelerograph(data):
            for item in data:
                if item not in seismograph_list:
                    data.remove(item)
            return data
        
        # Modify the group field here
        if self.gaps:
            self.gaps = self.gaps.upper()
            self.gaps = remove_accelerograph(self.gaps.split('\r\n'))
            self.count_gaps = len(self.gaps)

        if self.spikes:
            self.spikes = self.spikes.upper()
            self.spikes = remove_accelerograph(self.spikes.split('\r\n'))
            self.count_spikes = len(self.spikes)

        if self.blanks:
            self.blanks = self.blanks.upper()
            self.blanks = remove_accelerograph(self.blanks.split('\r\n'))
            self.count_blanks = len(self.blanks)

        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.tanggal} {self.jam}'
    
class OperatorModel(models.Model):
    name = models.CharField(max_length=100)
    nip = models.CharField(max_length=18)

    def __str__(self):
        return self.name

ChecklistSeiscomp/forms.py
from django import forms
from .models import ChecklistSeiscompModel, OperatorModel, StationListModel

# creating a form
class InputForm(forms.ModelForm):
    operator = forms.ModelChoiceField(
        queryset=OperatorModel.objects.all(), initial=0)

    # create meta class
    class Meta:
        # specify model to be used
        model = ChecklistSeiscompModel

        # specify fields to be used
        fields = '__all__'

        widgets = {
            'gaps': forms.Textarea(attrs={
                'class': 'tooltipped',
                'data-position': 'bottom',
                'data-tooltip': 'masukan kode stasiun yang mengalami gap, pisahkan dengan baris baru (enter)',
                'placeholder': 'contoh: ABCD',
            }),
            'spikes': forms.Textarea(attrs={
                'class': 'tooltipped',
                'data-position': 'bottom',
                'data-tooltip': 'masukan kode stasiun yang mengalami spike, pisahkan dengan baris baru (enter)',
                'placeholder': 'contoh: ABCD',
            }),
            'blanks': forms.Textarea(attrs={
                'class': 'tooltipped',
                'data-position': 'bottom',
                'data-tooltip': 'masukan kode stasiun yang mengalami blank, pisahkan dengan baris baru (enter)',
                'placeholder': 'contoh: ABCD',
            }),
            'slmon': forms.NumberInput(attrs={
                'class': 'tooltipped',
                'data-position': 'bottom',
                'data-tooltip': 'Jumlah sensor yang delay lebih dari 30 menit',
                'placeholder': 'Contoh: 30',
            }),
            'tanggal': forms.TextInput(attrs={
                'class': 'datepicker',
                'name': 'tanggal',
                'placeholder': 'yyyy-mm-dd',

            })
        }


class OperatorForm(forms.ModelForm):
    # create meta class
    class Meta:
        # specify model to be used
        model = OperatorModel

        # specify fields to be used
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Nama'}),
            'nip': forms.TextInput(attrs={'placeholder': 'NIP'}),
        }
        labels = {
            'name': ('Nama'),
            'nip': ('NIP'),
        }

class StationListForm(forms.ModelForm):
    # create meta class
    class Meta:
        # specify model to be used
        model = StationListModel

        # specify fields to be used
        fields = '__all__'
        widgets = {
            'kode': forms.TextInput(attrs={'placeholder': 'Kode Stasiun'}),
            'lokasi': forms.TextInput(attrs={'placeholder': 'Lokasi Stasiun'}),
            'tipe': forms.TextInput(attrs={'placeholder': 'Garansi atau Nongaransi'}),
        }
        labels = {
            'kode': ('Kode'),
            'stasiun': ('Lokasi Stasiun'),
            'tipe': ('Tipe Stasiun'),
        }

ChecklistSeiscomp/views.py
from django.http import HttpResponse
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect)
import openpyxl
from django.urls import reverse

# relative import of forms
from .models import ChecklistSeiscompModel, OperatorModel, StationListModel
from .forms import InputForm, OperatorForm, StationListForm


def create_view(request):
    # dictionary for initial data with
    # field names as keys
    context = {}
    context['dataset'] = ChecklistSeiscompModel.objects.all().order_by('-id')[:2]

    # add the dictionary during initialization
    input_form = InputForm(request.POST or None)
    if input_form.is_valid():
        input_form.save()
        # Resetting the form after it has been submitted.
        input_form = InputForm()

    context['input_form'] = input_form
    return render(request, "create_view.html", context)


def list_view(request):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # add the dictionary during initialization
    context["dataset"] = ChecklistSeiscompModel.objects.all().order_by('-id')

    return render(request, "list_view.html", context)


def update_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # fetch the object related to passed id
    obj = get_object_or_404(ChecklistSeiscompModel, id=id)

    # pass the object as instance in form
    form = OperatorForm(request.POST or None, instance=obj)

    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/"+id)

    # add form dictionary to context
    context["form"] = form

    return render(request, "update_view.html", context)


def operator_delete(request, id):
    ob = OperatorModel.objects.get(id=id)
    ob.delete()
    return HttpResponseRedirect(reverse('ChecklistSeiscomp:operator_view'))


def data_delete(request, id):
    ob = ChecklistSeiscompModel.objects.get(id=id)
    ob.delete()
    return HttpResponseRedirect(reverse('ChecklistSeiscomp:list_view'))


def operator_update(request, id):
    ob = OperatorModel.objects.get(id=id)
    ob.name = request.POST.get('field1')
    ob.save()
    return HttpResponseRedirect(reverse('ChecklistSeiscomp:operator_view'))


def operator_view(request):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # add the dictionary during initialization
    context["operators"] = OperatorModel.objects.all()

    add_operator_form = OperatorForm(request.POST or None)
    if add_operator_form.is_valid():
        add_operator_form.save()

        # Resetting the form after it has been submitted.
        add_operator_form = OperatorForm()

    context['add_operator_form'] = add_operator_form

    return render(request, "operator_view.html", context)


def edit_operator_name(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # fetch the object related to passed id
    obj = get_object_or_404(OperatorModel, id=id)

    # pass the object as instance in form
    form = OperatorForm(request.POST or None, instance=obj)

    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/"+id)

    # add form dictionary to context
    context["form"] = form

    return render(request, "operator_view.html", context)

def send_to_gcp_ss(request):
    import requests, ast

    url = 'https://script.google.com/macros/s/AKfycbxPVOb8TVUbu8q8c23d4jEJdTDEJZLp9me8Z7rkv0pbQ0m7jcNhcC6jwgt2bNfEe_vTmA/exec'
    data = ChecklistSeiscompModel.objects.all().order_by('-tanggal')[:2]

    data1 = {}
    if data[1].gaps:
        data1['gaps'] = ast.literal_eval(data[1].gaps)
    else:
        data1['gaps'] = []

    if data[1].spikes:
        data1['spikes'] = ast.literal_eval(data[1].spikes)
    else:
        data1['spikes'] = []

    if data[1].blanks:
        data1['blanks'] = ast.literal_eval(data[1].blanks)
    else:
        data1['blanks'] = []    

    data2 = {}
    if data[0].gaps:
        data2['gaps'] = ast.literal_eval(data[0].gaps)
    else:
        data2['gaps'] = []    

    if data[0].spikes:
        data2['spikes'] = ast.literal_eval(data[0].spikes)
    else:
        data2['spikes'] = [] 

    if data[0].blanks:
        data2['blanks'] = ast.literal_eval(data[0].blanks)
    else:
        data2['blanks'] = [] 

    all_data = {
        'kelompok': data[0].kelompok,
        'operator1': data[0].operator,
        'operator2': data[1].operator,
        'tanggal': date_range_to_string([data[1].tanggal, data[0].tanggal]),
        'data1': {
            'gaps': data1['gaps'],
            'spikes': data1['spikes'],
            'blanks': data1['blanks'],
        },
        'data2': {
            'gaps': data2['gaps'],
            'spikes': data2['spikes'],
            'blanks': data2['blanks'],
        },
    }
    
    response = requests.post(url, json=all_data)
    print(response.text)
    print(all_data)
    return HttpResponseRedirect("/checklist-seiscomp/create_view")

def format_date_indonesian(d):
    from datetime import date
    # Define Indonesian names for days and months
    days = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu']
    months = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 
              'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']

    # Get the day of the week, day of the month, month, and year from the date
    day_of_week = days[d.weekday()]
    day = d.day
    month = months[d.month - 1]
    year = d.year

    # Return the formatted date
    return f'{day_of_week}, {day} {month} {year}'

# def export_excel_instant(request):
#     """This function is used to export excel file containing last 2 records"""

#     from django.conf import settings
#     from .output_generator import generate_excel
#     import ast


#     data = ChecklistSeiscompModel.objects.all().order_by('-tanggal')[:2]
#     metadata = {'kelompok': data[0].kelompok,
#             'operator1': data[0].operator,
#             'operator2': data[1].operator,
#             'tanggal': date_range_to_string([data[1].tanggal, data[0].tanggal])}
    
#     data1 = {}
#     if data[1].gaps:
#         data1['gaps'] = ast.literal_eval(data[1].gaps)
#     else:
#         data1['gaps'] = []

#     if data[1].spikes:
#         data1['spikes'] = ast.literal_eval(data[1].spikes)
#     else:
#         data1['spikes'] = []

#     if data[1].blanks:
#         data1['blanks'] = ast.literal_eval(data[1].blanks)
#     else:
#         data1['blanks'] = []    

#     data2 = {}
#     if data[0].gaps:
#         data2['gaps'] = ast.literal_eval(data[0].gaps)
#     else:
#         data2['gaps'] = []    

#     if data[0].spikes:
#         data2['spikes'] = ast.literal_eval(data[0].spikes)
#     else:
#         data2['spikes'] = [] 

#     if data[0].blanks:
#         data2['blanks'] = ast.literal_eval(data[0].blanks)
#     else:
#         data2['blanks'] = [] 

#     # Get the path of the Excel file in static folder
#     file_path = str(settings.STATIC_ROOT) + '/ChecklistSeiscomp/template.xlsx'

#     # Save the workbook to a byte stream
#     response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
#     generate_excel(filename=file_path,
#                    response=response,
#                    metadata=metadata,
#                    data1=data1,
#                    data2=data2)
    
#     # Set the file name and attachment header
#     response['Content-Disposition'] = 'attachment; filename="data.xlsx"'
#     # Return the response
#     return response


def export_excel(request, id):
    """This function is used to export excel file containing last 2 records"""

    from django.conf import settings
    from .output_generator import generate_excel
    import ast

    dataset = ChecklistSeiscompModel.objects.get(id=id)
    shift = ''
    if dataset.jam == '12:00 WIB':
        shift = 'SHIFT PAGI'
    elif dataset.jam == '18:00 WIB':
        shift = 'SHIFT SIANG'    
    else:
        shift = 'SHIFT MALAM'

    metadata = {'kelompok': dataset.kelompok,
            'operator': dataset.operator,
            'tanggal': format_date_indonesian(dataset.tanggal),
            'shift': shift,
            'jam': dataset.jam,
            }
    
    data = {}
    if dataset.gaps:
        data['gaps'] = ast.literal_eval(dataset.gaps)
    else:
        data['gaps'] = []

    if dataset.spikes:
        data['spikes'] = ast.literal_eval(dataset.spikes)
    else:
        data['spikes'] = []

    if dataset.blanks:
        data['blanks'] = ast.literal_eval(dataset.blanks)
    else:
        data['blanks'] = []   

    # Get the path of the Excel file in static folder
    file_path = str(settings.STATIC_ROOT) + '/ChecklistSeiscomp/template.xlsx'

    # Save the workbook to a byte stream
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    generate_excel(filename=file_path,
                   response=response,
                   metadata=metadata,
                   data=data,
                   )
    
    # Set the file name and attachment header
    response['Content-Disposition'] = f'attachment; filename="CS_{dataset.tanggal}_{shift.split()[1]}.xlsx"'
    # Return the response
    return response

def download_file(real_file_id):
    import io

    import google.auth
    from googleapiclient.discovery import build
    from googleapiclient.errors import HttpError
    from googleapiclient.http import MediaIoBaseDownload
    from secret_settings import GSHEETS_CREDS
    """Downloads a file
    Args:
        real_file_id: ID of the file to download
    Returns : IO object with location.

    Load pre-authorized user credentials from the environment.

ChecklistSeiscomp/templates/base.html
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}

    <title>Checklist Seiscomp</title>
    {% block css %}
    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Materialize CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
        integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />

    <!-- custom style -->
    <link rel="stylesheet" href="{% static 'ChecklistSeiscomp/style.css' %}">

    {% endblock css %}

    {% block custom_css %}
    {% endblock custom_css %}
</head>

<body>
    <nav class="nav-wrapper blue darken-1">
        <div class="container">
            <div class="nav-wrapper blue darken-1">
                {% if user.is_authenticated %}
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <a href="https://github.com/ftharyanto/eBAST" target="_blank" class="tooltipped right"
                    data-tooltip="Source Code"><i class="fa-brands fa-github"></i></a>
                <!-- <a href="{% url 'accounts:login' %}" class="right" style="margin-right: 1rem;">Logout</a> -->

                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    {% with request.resolver_match.url_name as url_name %}
                    <!-- <li class="{% if url_name == 'statistic_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:statistic_view' %}">Statistic</a></li> -->
                    <li class="{% if url_name == 'create_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:create_view' %}">Input Data</a></li>
                    <li class="{% if url_name == 'list_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:list_view' %}">Inventory</a></li>
                    <li class="{% if url_name == 'operator_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:operator_view' %}">Operator</a></li>
                    <li class="{% if url_name == 'station_list_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:station_list_view' %}">Station List</a></li>
                    {% endwith %}
                </ul>

                {% else %}
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <a href="https://github.com/ftharyanto/eBAST" target="_blank" class="tooltipped right"
                    data-tooltip="Source Code"><i class="fa-brands fa-github"></i></a>

                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    {% with request.resolver_match.url_name as url_name %}
                    <!-- <li class="{% if url_name == 'statistic_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:statistic_view' %}">Statistic</a></li> -->
                    <li class="{% if url_name == 'create_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:create_view' %}">Input Data</a></li>
                    <li class="{% if url_name == 'list_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:list_view' %}">Inventory</a></li>
                    <li class="{% if url_name == 'operator_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:operator_view' %}">Operator</a></li>
                    <li class="{% if url_name == 'station_list_view' %}active{% endif %}"><a
                            href="{% url 'ChecklistSeiscomp:station_list_view' %}">Station List</a></li>
                    {% endwith %}
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
        {% with request.resolver_match.url_name as url_name %}
        <li class="{% if url_name == 'create_view' %}active{% endif %}"><a
                href="{% url 'ChecklistSeiscomp:create_view' %}">Input Data</a></li>
        <li class="{% if url_name == 'list_view' %}active{% endif %}"><a
                href="{% url 'ChecklistSeiscomp:list_view' %}">Inventory</a></li>
        <li class="{% if url_name == 'operator_view' %}active{% endif %}"><a
                href="{% url 'ChecklistSeiscomp:operator_view' %}">Operator</a></li>
        <li class="{% if url_name == 'station_list_view' %}active{% endif %}"><a
                href="{% url 'ChecklistSeiscomp:station_list_view' %}">Station List</a></li>
        <li>
            <div class="divider"></div>
        </li>
        <li><a href="https://github.com/ftharyanto/eBAST" target="_blank" class="down"><i
                    class="fa-brands fa-github"></i> Source Code</a></li>
        {% endwith %}

    </ul>

    
    {% if messages %}
    {% for message in messages %}
    <script>
        M.toast({ html: {{ message }})
    </script>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
        integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.sidenav');
            M.Sidenav.init(elems);
        });

        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.tooltipped');
            M.Tooltip.init(elems);
        });

        var tds = document.getElementsByTagName("td");
        for (var i = 0; i < tds.length; i++) {
            if (tds[i].innerHTML == " None " || tds[i].innerHTML == "  ") {
                tds[i].innerHTML = " None "
                tds[i].style.color = "gray";
                tds[i].style.fontStyle = "italic"
            }
        }
    </script>

    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

ChecklistSeiscomp/templates/detail_view.html
{% extends "base.html" %}
{% load materializecss %}

{% block content %}
<div class="container" style="padding-top: 2rem;">
    {% for item in data %}
    <p><b>Tanggal:</b> {{ item.tanggal|date:'Y-m-d' }}</p>
    <p><b>Kelompok:</b> {{ item.kelompok }}</p>
    <p><b>Operator:</b> {{ item.operator }}</p>
    <p><b>Jam:</b> {{ item.jam }}</p>
    <p><b>Count Gaps:</b> {{ item.count_gaps }}</p>
    <p><b>Count Spikes:</b> {{ item.count_spikes }}</p>
    <p><b>Count Blanks:</b> {{ item.count_blanks }}</p>
    <p><b>Gaps:</b> {{ item.gaps }}</p>
    <p><b>Spikes:</b> {{ item.spikes }}</p>
    <p><b>Blanks:</b> {{ item.blanks }}</p>
    <p><b>Slmon:</b> {{ item.slmon }}</p>
    {% endfor %}
</div>

{% endblock content %}

{% block javascript %}
{% endblock javascript %}

ChecklistSeiscomp/templates/list_view.html
{% extends "base.html" %}
{% load materializecss %}

{% block content %}
<div class="container" style="padding-top: 2rem;">


    <a class="waves-effect waves-light btn blue darken-1" href="{% url 'ChecklistSeiscomp:create_view' %}"><i
            class="material-icons left">add</i>tambah data</a>
    <a style="display: none;" class="waves-effect waves-light btn red darken-1" href="/"><i
            class="material-icons left">picture_as_pdf</i>Buat
        Laporan PDF</a>

    <table>
        <tr>
            <th>Tanggal</th>
            <th>Kelompok</th>
            <th>Operator</th>
            <th>Jam</th>
            <th>Gaps</th>
            <th>Spikes</th>
            <th>Blanks</th>
            <th>Slmon</th>
            <th>Aksi</th>
        </tr>
        {% for data in dataset %}
        <tr>
            <td> <a href="{% url 'ChecklistSeiscomp:detail_view' data.id %}">{{ data.tanggal|date:'Y-m-d' }}</a> </td>
            <td> {{ data.kelompok }} </td>
            <td> {{ data.operator }} </td>
            <td> {{ data.jam }} </td>
            <td> {{ data.count_gaps }} </td>
            <td> {{ data.count_spikes }} </td>
            <td> {{ data.count_blanks }} </td>
            <td> {{ data.slmon }} </td>
            <td>
                <a class="waves-effect waves-light btn green darken-1 tooltipped" data-position="bottom" data-tooltip="Export to an excel file" href="{% url 'ChecklistSeiscomp:export_excel' data.id %}"><i class="fa-solid fa-file-excel"></i></a>
                <a class="waves-effect waves-light btn" id="edit-{{ operator.id }}" style="display: none;"><i
                        class="material-icons center">edit</i></a>
                <a id="data_del_btn{{ data.id }}" onmouseup="data_del({{ data.id }})"
                    class="waves-effect waves-light btn red tooltipped" data-position="bottom" data-tooltip="Delete this record"  id="delete-{{ operator.id }}"><i
                        class="material-icons center">delete</i></a>
                <a id="delete_confirmation_{{ data.id }}" href="{% url 'ChecklistSeiscomp:data_delete' data.id %}"
                    class="waves-effect waves-light btn red" style="visibility: hidden;"><i
                        class="material-icons center"></i>yes</a>

            </td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock content %}

{% block javascript %}
<script>
    var data_del = function (id) {
        var delBtn = document.getElementById('delete_confirmation_' + id)
        delBtn.style.visibility = 'visible';
        var delBtnNo = document.getElementById('data_del_btn' + id);
        delBtnNo.innerHTML = "no";
        delBtnNo.classList.remove("red");
        delBtnNo.classList.add("white", "black-text");
        delBtnNo.onmouseup = '';

        return delBtnNo.setAttribute('href', '/checklist-seiscomp/list_view')
    }

</script>
{% endblock javascript %}

ChecklistSeiscomp/templates/operator_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete this record?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete it</button>
    <a href="{% url 'operator_view' %}">No, take me back</a>
  </form>
{% endblock %}

ChecklistSeiscomp/templates/update_view.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
 
        <!-- form as paragraph -->
        {{ add_operator_form.as_p }}
 
        <input type="submit" value="Update">
    </form>
 
</div>